---
title: "Profile visualisation"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(shiny)
source("functions/profile_numb.r")

pigments <- c("fuco", "peri", "hex", "but", "allo", "tchlb", "zea")

hplc <- read_csv("Data/argo/hplc_argo")
ref <- read_csv("Data/argo/ref.csv")
ref_bis <- read_csv("Data/argo/ref_bis")
map_vec <- read_csv("Data/map_vec")
first_profiles <- read_csv("Data/argo/first_profiles")
first_profiles <- first_profiles[-1,]
first_profiles$date <- date(first_profiles$date)
ref <- bind_rows(ref, ref_bis)

first_profiles$depth <- round(first_profiles$pres)
first_profiles$lon <- round(first_profiles$lon, 2)
first_profiles$lat <- round(first_profiles$lat, 2)

hplc <- left_join(hplc, ref, by = c("id" = "lovbio"))
first_profiles$number <- as.numeric(first_profiles$id)
first_profiles <- left_join(first_profiles, ref)
first_profiles <- left_join(first_profiles, ref_bis)

merged <- read_csv("Data/merged_argo")

merged <- select(merged, lon.y, lat.y, chla, tchla, depth, lovbio)

profiles <- left_join(first_profiles, merged, by = c("chla", "lon" = "lon.y", "lat" = "lat.y", "depth"))
```


Column {data-width=400}
-----------------------------------------------------------------------

### Profile

```{r}
selectInput("lovbio", label = "lovbio id",
            choices = sort(unique(first_profiles$lovbio)), selected = "lovbio012b")

renderPlot({
  ggplot()+
  geom_path(aes(x = chla_adjusted, y = -pres), data = filter(first_profiles, lovbio == input$lovbio), colour = "limegreen", size = 1.1)+
  geom_point(aes(x = tchla, y = - depth), data = filter(merged, lovbio == input$lovbio), colour = "Red")+
  ggtitle(input$lovbio)+
  theme_bw()
})
```

Column {data-width=350}
-----------------------------------------------------------------------

### Map

```{r}

renderPlot({ggplot()+
  geom_polygon(aes(x = long, y = lat, group = group), data = map_vec)+
  geom_point(aes(x = lon, y = lat), data = filter(first_profiles, lovbio == input$lovbio), colour = "Red")+
  coord_quickmap()+
    ggtitle(paste("lon :", unique(first_profiles$lon[first_profiles$lovbio == input$lovbio]), "; lat :", unique(first_profiles$lat[first_profiles$lovbio == input$lovbio]), sep = " "))+
  theme_bw()
})
```

### Fluo vs HPLC tchla

```{r}
renderPlot({ggplot()+
  geom_point(aes(x = tchla, y = chla), data = merged)+
  geom_point(aes(x = tchla, y = chla), data = filter(merged, lovbio == input$lovbio), colour = "Red")+
    theme_bw()
})
```

