---
title: "R Notebook"
output: html_notebook
code: "Hide"
---

```{r message=FALSE, warning=FALSE, paged.print=FALSE}
library(tidyverse)
library(readxl)
library(janitor)
library(lubridate)

biosope <- read_csv("Biosope/Data/biosope")
spectre <- read_excel("Biosope/Data/Spectres_annick.xlsx")
spectre <- clean_names(spectre)
spectre440<- filter(spectre, lambda == 440)
spectre470 <- filter(spectre, lambda == 470)


biosope <- biosope %>% mutate(photo_440 = peri * spectre440$peri + but * spectre440$x19_bf + fuco * spectre440$fuco + allo * spectre440$allox + chla * spectre440$chl_a,
                              protect_440 = zea * spectre440$zea,
                              photo_470 = peri * spectre470$peri + but * spectre470$x19_bf + fuco * spectre470$fuco + allo * spectre470$allox + chla * spectre470$chl_a,
                              protect_470 = zea * spectre470$zea, 
                              ratio_photo = photo_440/fluo_urel,
                              ratio_protect = protect_440/fluo_urel)
```


Plot du rapport entre l'absorbance photosynthétique à 440 et à 470 (photo_440/photo_470) en fonction de la fluo. (sur la surface cad au dessus de 20m)
```{r message=FALSE, warning=FALSE, paged.print=FALSE}
ggplot(filter(biosope, depth < 20), aes(x = fluo_urel))+
  geom_point(aes(y = photo_440/photo_470))+
  theme_bw()
```


Plot du rapport photo_440/photo_470 sur le profil de la station 8 (St8)
```{r}
ggplot(filter(biosope, site == "St8"))+
  geom_point(aes(x = photo_440/photo_470, y = -depth))+
  theme_bw()
```

Plot de la Chla HPLC du profil pour info
```{r}
ggplot(filter(biosope, site == "St8"))+
  geom_point(aes(x = tchla, y = -depth))+
  theme_bw()
```


